baseURL = "https://aemiej.netlify.app/"
disqusShortname = ""
languageCode = "en-us"
paginate = "3"
summaryLength = "10"
theme = "northendlab-hugo"
title = "AemieJ - Portfolio"
[markup.goldmark.renderer]
unsafe = true
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "tools"
name = "Tools"
weight = 2
[[menu.main]]
URL = "author/aemie-jariwala"
name = "About"
weight = 1
[[menu.main]]
URL = "/resume.pdf"
name = "Resume"
weight = "2"
[[menu.main]]
URL = "tools"
name = "Tools"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "This is meta description"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.png"
title = "Hi, I'm Aemie Jariwala. <br> I fancy <a href='#'>minimalistic</a> designs."
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/aemie.jariwala"
[[params.social]]
icon = "ti-github"
link = "https://github.com/AemieJ"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/aemie-jariwala-36a682179/"
